print('  Hello there! I am Maryan Maxwell. I go by Max.')
print('  And one of my favorite shapes would probably have to be this lad.')
print('')
print('    His name is Fabian.')
print('                                              wwwWW O')
print('                                                   wWWw')
print('                        /\                              WW')
print('                        \/                               w')
print('                     V       /\                          wW')
print('                             \/                       wWW ')                       
print('                                              wwWWWW')
print('                _--__                 __WWWWWWWWwwwwwww ooo_            _--_')
print('              -      -__         __WWWWWWWWWWwwwwwwwwwwwwwwww ooo_    _-    -_')
print('             -           --_wwwWWWWWWWWWw ----\    /---- WWWWWW OOO_-         -')
print('            -      -_        wWWWWWWww  /                \ WWWWW OO    _-      -')
print('            -         ---    wwWWWWw   |     U      U    |  WWW OO  --          -')
print('             -            --wwWWWww    |     Ul     Ul   | wWWW O               - ')   
print('              -             wwWWWw      \_   WU     WU  _/wWW O                -')
print('               -             wWWWw__-----__               __----)            _-')
print('                --           wWWWWw///////                  //////        _-       /\ ')
print('                   ---       wWWWWWw ///  __       __\      __  ///)     -         \/   V')
print('      /\              --- ___wWWWWWw     o  \______ \ ____/        )_-ww ')
print('      \/         wWWw    wWWWWWWWWWWWWWWW OO  \wwwuuuuuu/       )WWWWWWWw O')
print('         V        WWWWWWWWWwwWWWWWWWWWWW\      \----wwu/      --WWWWWwwwww OO')
print('                     WWWWWWWWWWWWWWWWWWW----____\____-/___---WWWWWWWWWWWWwww O')
print('                   wWWWWWWWWWWWWWWWWWWWWWWWWww         /WWWWWWWwwwwwwwww OO')
print('              wwWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\_    _WWWWWWWWWWWww O')
print('           wwwWWWWWWWWWWWWWWWWWWWWWWWWWWW|uuuu|     ---- u\WWWWw O')
print('             wwwWWWWWWWWWWWWWWWWWWWWWWWWWww|                _|                 /\ ')
print('                 WWWWWWWWWWWWWWWWWWWWWWWWwww\--__   _     _-/                  \/') 
print('                wwwWWWWWWWWWWWWWWWWWWWWWWWWWWw \     --_-                   V')
print('                          wwWWWWWWWWWWww         \___   - /                         V')
print('                               wwww                 \   /')
print('                                                     |/')
print('')
print('  ... He is a complex shape but very friendly nonetheless.')
